CREATE TABLE "Courses" (
	"course_code" number(10) NOT NULL UNIQUE,
	"course_title" varchar2(255) NOT NULL UNIQUE,
	"course_credits" number(10) NOT NULL,
	"course_syllabus" varchar2(255),
	"course_pre_req" varchar2(255),
	PRIMARY KEY ("course_code")
);

CREATE TABLE "Course_Offerings" (
	"class_nbr" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"year" number(10) NOT NULL,
	"semester" number(10) NOT NULL,
	"timings" number(10) NOT NULL,
	"classroom" varchar2(255) NOT NULL,
	"instructor_erp" number(10) NOT NULL,
	PRIMARY KEY ("class_nbr")
);

CREATE TABLE "instructor" (
	"instructor_erp" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"instructor_name" varchar2(255) NOT NULL,
	"department" varchar2(255) NOT NULL,
	"job_title" varchar2(255) NOT NULL,
	PRIMARY KEY ("instructor_erp")
);

CREATE TABLE "Students" (
	"student_erp" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"student_name" varchar2(255) NOT NULL,
	"date_of_birth" date NOT NULL,
	"email" varchar2(255) NOT NULL,
	"program" varchar2(255) NOT NULL,
	PRIMARY KEY ("student_erp")
);

CREATE TABLE "enrollment" (
	"student_erp" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"class_nbr" number(10) NOT NULL,
	"grade" varchar2(255) NOT NULL,
	PRIMARY KEY ("student_erp", "class_nbr")
);

CREATE TABLE "pre_req" (
	"course_code" number(10) NOT NULL UNIQUE,
	"pre_req_id" number(10) NOT NULL UNIQUE,
	PRIMARY KEY ("course_code", "pre_req_id")
);


ALTER TABLE "Course_Offerings" ADD CONSTRAINT "Course_Offerings_fk5" FOREIGN KEY ("instructor_erp") REFERENCES "instructor"("instructor_erp");


ALTER TABLE "enrollment" ADD CONSTRAINT "enrollment_fk0" FOREIGN KEY ("student_erp") REFERENCES "Students"("student_erp");

ALTER TABLE "enrollment" ADD CONSTRAINT "enrollment_fk1" FOREIGN KEY ("class_nbr") REFERENCES "Course_Offerings"("class_nbr");
ALTER TABLE "pre_req" ADD CONSTRAINT "pre_req_fk0" FOREIGN KEY ("course_code") REFERENCES "Courses"("course_code");

ALTER TABLE "pre_req" ADD CONSTRAINT "pre_req_fk1" FOREIGN KEY ("pre_req_id") REFERENCES "Courses"("course_code");