CREATE TABLE "stadium" (
	"stadium_nbr" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"stadium_city" varchar2(255) NOT NULL,
	"stadium_country" varchar2(255) NOT NULL,
	"stadium_capacity" number(10) NOT NULL,
	"stadium_name" varchar2(255) NOT NULL,
	PRIMARY KEY ("stadium_nbr")
);

CREATE TABLE "match" (
	"match_nbr" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"umpire_1" varchar2(255) NOT NULL,
	"umpire_2" varchar2(255) NOT NULL,
	"team_1" varchar2(255) NOT NULL,
	"team_2" varchar2(255) NOT NULL,
	"winner_team" varchar2(255) NOT NULL,
	"man_of_match" number(10) NOT NULL,
	"stadium" number(10) NOT NULL,
	"match_time" date NOT NULL UNIQUE,
	PRIMARY KEY ("match_nbr")
);

CREATE TABLE "team" (
	"country_name" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"captain" varchar2(255) NOT NULL,
	PRIMARY KEY ("country_name")
);

CREATE TABLE "player" (
	"player_id" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"player_name" varchar2(255) NOT NULL,
	"player_country" varchar2(255) NOT NULL,
	PRIMARY KEY ("player_id")
);

CREATE TABLE "umpire" (
	"umpire_id" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"umpire_name" varchar2(255) NOT NULL,
	"umpire_country" varchar2(255) NOT NULL,
	PRIMARY KEY ("umpire_id")
);

CREATE TABLE "player_performance" (
	"match_id" number(10,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	"player_id" number(10) NOT NULL,
	"runs" number(10) NOT NULL,
	"wickets" number(10) NOT NULL,
	PRIMARY KEY ("match_id", "player_id")
);


ALTER TABLE "match" ADD CONSTRAINT "match_fk1" FOREIGN KEY ("umpire_1") REFERENCES "umpire"("umpire_id");

ALTER TABLE "match" ADD CONSTRAINT "match_fk2" FOREIGN KEY ("umpire_2") REFERENCES "umpire"("umpire_id");

ALTER TABLE "match" ADD CONSTRAINT "match_fk3" FOREIGN KEY ("team_1") REFERENCES "team"("country_name");

ALTER TABLE "match" ADD CONSTRAINT "match_fk4" FOREIGN KEY ("team_2") REFERENCES "team"("country_name");

ALTER TABLE "match" ADD CONSTRAINT "match_fk5" FOREIGN KEY ("winner_team") REFERENCES "team"("country_name");

ALTER TABLE "match" ADD CONSTRAINT "match_fk6" FOREIGN KEY ("man_of_match") REFERENCES "player"("player_id");

ALTER TABLE "match" ADD CONSTRAINT "match_fk7" FOREIGN KEY ("stadium") REFERENCES "stadium"("stadium_nbr");
ALTER TABLE "team" ADD CONSTRAINT "team_fk1" FOREIGN KEY ("captain") REFERENCES "player"("player_id");
ALTER TABLE "player" ADD CONSTRAINT "player_fk2" FOREIGN KEY ("player_country") REFERENCES "team"("country_name");

ALTER TABLE "player_performance" ADD CONSTRAINT "player_performance_fk0" FOREIGN KEY ("match_id") REFERENCES "match"("match_nbr");

ALTER TABLE "player_performance" ADD CONSTRAINT "player_performance_fk1" FOREIGN KEY ("player_id") REFERENCES "player"("player_id");